=== mserra69/tema03/ejercicio5.dtd
<!ELEMENT CurriculumVitae (DatosPersonales, Resumen, ExperienciaLaboral, Educacion, Habilidades, Certificaciones)>
<!ELEMENT DatosPersonales (Nombre, Apellidos, Telefono, Email, Direccion)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellidos (#PCDATA)>
<!ELEMENT Telefono (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Direccion (#PCDATA)>

<!ELEMENT Resumen (Perfil)>
<!ELEMENT Perfil (#PCDATA)>

<!ELEMENT ExperienciaLaboral (Trabajo+)>
<!ELEMENT Trabajo (Puesto, Empresa, FechaInicio, FechaFin, Descripcion)>
<!ELEMENT Puesto (#PCDATA)>
<!ELEMENT Empresa (#PCDATA)>
<!ELEMENT FechaInicio (#PCDATA)>
<!ELEMENT FechaFin (#PCDATA)>
<!ELEMENT Descripcion (#PCDATA)>

<!ELEMENT Educacion (Titulo+)>
<!ELEMENT Titulo (Grado, Institucion, Fecha)>
<!ELEMENT Grado (#PCDATA)>
<!ELEMENT Institucion (#PCDATA)>
<!ELEMENT Fecha (#PCDATA)>

<!ELEMENT Habilidades (Habilidad+)>
<!ELEMENT Habilidad (#PCDATA)>

<!ELEMENT Certificaciones (Certificacion+)>
<!ELEMENT Certificacion (Nombre_titulo, Autoridad, FechaObtencion)>
<!ELEMENT Nombre_titulo (#PCDATA)>
<!ELEMENT Autoridad (#PCDATA)>
<!ELEMENT FechaObtencion (#PCDATA)>

<!ATTLIST CurriculumVitae lang CDATA #REQUIRED>

=== mserra69/tema03/ejericio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CurriculumVitae SYSTEM "ejercicio5.dtd">

<CurriculumVitae lang="es">
    <DatosPersonales>
        <Nombre>Miquel</Nombre>
        <Apellidos>Serra Costa</Apellidos>
        <Telefono>661102031</Telefono>
        <Email>llauraor13@yahoo.com</Email>
        <Direccion>Calle Dénia,31,Pedreguer 03750</Direccion>
    </DatosPersonales>
   <Resumen>
        <Perfil>Técnico de redes con más de 4 años de experiencia en administración y gestión de reds.</Perfil>
    </Resumen>
    <ExperienciaLaboral>
        <Trabajo>
            <Puesto>Técnico de Redes</Puesto>
            <Empresa>Redes Enredadas</Empresa>
            <FechaInicio>03-2020</FechaInicio>
            <FechaFin>Actualidad</FechaFin>
            <Descripcion>Administración de redes LAN/WAN, gestión de firewalls y soporte técnico a usuarios.</Descripcion>
        </Trabajo>
    </ExperienciaLaboral>
    <Educacion>
        <Titulo>
            <Grado>Técnico Superior en Administración de Sistemas Informáticos en Red</Grado>
            <Institucion>Instituto I.E.S. La Mar Xàbia</Institucion>
            <Fecha>2010-2012</Fecha>
        </Titulo>
    </Educacion>
    <Habilidades>
        <Habilidad>Configuración de Routers y Switches</Habilidad>
        <Habilidad>Gestión de Firewall</Habilidad>
        <Habilidad>Protocolos TCP/IP</Habilidad>
        <Habilidad>Diagnóstico de Redes</Habilidad>
        <Habilidad>Trabajo en equipo</Habilidad>
    </Habilidades>
    <Certificaciones>
        <Certificacion>
            <Nombre_titulo>CCNA</Nombre_titulo>
            <Autoridad>Cisco</Autoridad>
            <FechaObtencion>03-2015</FechaObtencion>
        </Certificacion>
    </Certificaciones>
</CurriculumVitae>
